name: Deploy Kong DB-less config for EC2

on:
  push:
    paths:
      - kong.yaml

jobs:
  kong-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deck
        uses: kong/setup-deck@v1
        with:
          version: 1.7.0

      - name: Validate Kong DB-less config
        run: |
         deck validate -s kong.yaml

      - name: Deploy to AWS
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.EC2_SSH_KEY }}"
          scp -o StrictHostKeyChecking=no kong.yaml ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/kong.yaml

      - name: Move and Restart Kong on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            mv /home/ec2-user/kong.yaml /etc/kong/kong.yaml
            ls -al
            sudo kong restart